### PR TITLE
Pretty-print `throws` clause in method signatures

### LINKED ISSUE #147: Add `throws` clause to pretty-printed signature
e.g. `public void method() throws OutOfBoundsException` currently does not include the `throws` in the signature

### PR DESCRIPTION
**Pull request by Strum355**
Add 'throws' field to `MethodSignature` in semanticdb for implementing pretty-printing, to be upstreamed to semanticdb spec. 
This is a fairly trivial change so it shouldnt be a big deal to upstream.

Closes #147

### CODE REVIEW

File: tests/minimized/src/main/java/minimized/Methods.java [hunk 1]
```diff
@@ -17,7 +17,7 @@ private static String staticOverload(String value) {
     return value + "1";
   }
 
-  public static String app(int n, String m) {
+  public static String app(int n, String m) throws RuntimeException {
```
Comment (olafurpg) [inline tests/minimized/src/main/java/minimized/Methods.java:20]: I'm surprised that epoxy doesn't use `throws` anywhere. Checked exceptions are IMO one of the biggest pains of working with Java. Can we add one test case where the exception has type parameters just to stress the code path that `throws` is `Type` and not symbols

**Review by olafurpg — CHANGES_REQUESTED** [review]
I'm investigating in #163 why the CI is failing. 

One minor comments, otherwise looks good

File: tests/minimized/src/main/java/minimized/Methods.java (hunk 1 above)
Comment (Strum355) [reply tests/minimized/src/main/java/minimized/Methods.java:20]: Turns out custom exceptions (that extend Exception/Throwable) cant have type parameters :thinking:

Comment (olafurpg) [reply tests/minimized/src/main/java/minimized/Methods.java:20]: Where did you find examples with type parameters? Are they only in the JDK?

Comment (Strum355) [reply tests/minimized/src/main/java/minimized/Methods.java:20]: https://sourcegraph.com/search?q=context:global+%28+throws+%5Ba-zA-Z%5D%2B%3C%5BA-Z%5D%5Ba-zA-Z%5D*%3E%29+lang:java&patternType=regexp&case=yes

Comment (Strum355) [reply tests/minimized/src/main/java/minimized/Methods.java:20]: Not exactly "conclusive" or "proving" evidence by any means :grin:

Comment (Strum355) [reply tests/minimized/src/main/java/minimized/Methods.java]: Ive added an additional exception to the signature to make up for it. Gonna merge :+1:
