### PR TITLE
handle unresolved annotation parameter tree differences

### LINKED ISSUE #186: ClassCastException: com.sun.tools.javac.tree.JCTree$JCLiteral cannot be cast to com.sun.tools.javac.tree.JCTree$JCAssign
```
 java.lang.ClassCastException: com.sun.tools.javac.tree.JCTree$JCLiteral cannot be cast to com.sun.tools.javac.tree.JCTree$JCAssign

        at com.sourcegraph.semanticdb_javac.SemanticdbVisitor.semanticdbAnnotation (SemanticdbVisitor.java:399)
        at com.sourcegraph.semanticdb_javac.SemanticdbVisitor.semanticdbAnnotations (SemanticdbVisitor.java:384)
        at com.sourcegraph.semanticdb_javac.SemanticdbVisitor.emitSymbolInformation (SemanticdbVisitor.java:98)
        at com.sourcegraph.semanticdb_javac.SemanticdbVisitor.emitSymbolOccurrence (SemanticdbVisitor.java:87)
        at com.sourcegraph.semanticdb_javac.SemanticdbVisitor.visitVariable (SemanticdbVisitor.java:196)
        at com.sourcegraph.semanticdb_javac.SemanticdbVisitor.visitVariable (SemanticdbVisitor.java:29) 
```

### PR DESCRIPTION
**Pull request by Strum355**
In certain situations when an annotation symbol cannot be resolved, the tree types of parameters are not `JCAssign`. 
This PR addresses the cast exceptions caused by this.

The `SignatureFormatter` is also modified to accept the new semanticdb output but from what I have seen, the codepaths arent reached for those unresolved annotations (typically getting the `__root__/` symbol).

Closes #186

### CODE REVIEW

File: semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/SemanticdbVisitor.java [hunk 1]
```diff
@@ -23,6 +23,7 @@
 import java.util.*;
 import java.util.stream.Collectors;
 
+import static com.sourcegraph.semanticdb_javac.Debugging.pprint;
```
Comment (olafurpg) [inline semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/SemanticdbVisitor.java:26]: Remove

**Review by olafurpg — APPROVED** [review]
LGTM 👍 It would be nice to have a targeted test case, if only to validate that we can test code with compile errors. However, I'm OK with merging this without tests. It's always good to get rid of unsafe casts

**Comment by Strum355** [comment]
Tried recreating the issue in an isolated case, but even there I would get a JCAssign tree :disappointed:
