### PR TITLE
copy JDK_HOME bootstrap files to forwarding toolchain directory for Kotlin

### LINKED ISSUE #417: indexing Kotlin repository fails when Gradle Java toolchains is enabled
When trying to index https://github.com/fwcd/kotlin-language-server, I get the following output:
```
 lsif-java index
$ /tmp/kotlin-language-server/gradlew --init-script /tmp/lsif-java6254693687289437253/java-toolchains.gradle lsifDetectJavaToolchains
Downloading https://services.gradle.org/distributions/gradle-7.3.1-bin.zip
...........10%...........20%...........30%...........40%...........50%...........60%...........70%...........80%...........90%...........100%

Welcome to Gradle 7.3.1!

Here are the highlights of this release:
 - Easily declare new test suites in Java projects
 - Support for Java 17
 - Support for Scala 3

For more details see https://docs.gradle.org/7.3.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)
> Task :lsifDetectJavaToolchains
> Task :grammars:lsifDetectJavaToolchains
> Task :server:lsifDetectJavaToolchains
> Task :shared:lsifDetectJavaToolchains

BUILD SUCCESSFUL in 1m 55s
4 actionable tasks: 4 executed
$ /tmp/kotlin-language-server/gradlew --no-daemon --init-script /tmp/lsif-java6254693687289437253/init-script.gradle -Porg.gradle.java.installations.auto-detect=false -Porg.gradle.java.installations.auto-download=false -Porg.gradle.java.installations.paths=/tmp/lsif-java6254693687289437253/1.11 clean compileTestJava compileTestKotlin lsifJavaDependencies
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.3.1/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 
> Task :clean
> Task :server:clean UP-TO-DATE
> Task :shared:clean UP-TO-DATE
> Task :compileKotlin NO-SOURCE
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :compileTestKotlin NO-SOURCE
> Task :compileTestJava NO-SOURCE

> Task :shared:compileKotlin FAILED
e: No class roots are found in the JDK path: /tmp/lsif-java6254693687289437253/1.11

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':shared:compileKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.


See https://docs.gradle.org/7.3.1/userguide/command_line_interface.html#sec:command_line_warnings
BUILD FAILED in 15s
4 actionable tasks: 2 executed, 2 up-to-date
```

Just running `./gradlew compileKotlin` succeeds with 0 errors. Happens with both JDK 8 and 11, with and without $JAVA_HOME set

### PR DESCRIPTION
**Pull request by Strum355**
Closes #417 

### Test plan

I tested this on https://github.com/fwcd/kotlin-language-server :slightly_smiling_face:

### CODE REVIEW

**Comment by Strum355** [comment]
I might have to change this to copy everything, as symbolic links under Windows has historically required elevated permissions. What do you think? @olafurpg

File: lsif-java/src/main/scala/com/sourcegraph/lsif_java/buildtools/GradleJavaCompiler.scala [hunk 1]
```diff
@@ -98,6 +98,16 @@ case class GradleJavaCompiler(languageVersion: String, javacPath: Path) {
       )
       .toFile
       .setExecutable(true)
+    // for compileKotlin when using jvm toolchains
+    val libPath = dir.resolve("lib")
+    Files
+      .walk(javacPath.getParent.getParent.resolve("lib"))
+      .forEach(source => {
+        val destination = libPath.resolve(
+          javacPath.getParent.getParent.resolve("lib").relativize(source)
```
Comment (varungandhi-src) [inline lsif-java/src/main/scala/com/sourcegraph/lsif_java/buildtools/GradleJavaCompiler.scala:107]: Maybe hoist out `javacPath.getParent.getParent.resolve("lib")` and give it a name?

File: tests/buildTools/src/test/scala/tests/GradleBuildToolSuite.scala [hunk 2]
```diff
@@ -287,6 +287,28 @@ class GradleBuildToolSuite extends BaseBuildToolSuite {
     4
   )
 
+  List("8", "11").foreach { version =>
```
Comment (varungandhi-src) [inline tests/buildTools/src/test/scala/tests/GradleBuildToolSuite.scala:290]: Thanks for adding this test. Should we also add "14" and "17" here, or are we only generally testing Java 8 and Java 11?

Comment (Strum355) [reply tests/buildTools/src/test/scala/tests/GradleBuildToolSuite.scala:290]: The main change that is relevant here divides JDK 8 and everything that comes after, and 11 just happens to be the most common one :shrug:

File: lsif-java/src/main/scala/com/sourcegraph/lsif_java/buildtools/GradleJavaCompiler.scala [hunk 3]
```diff
@@ -98,6 +98,29 @@ case class GradleJavaCompiler(languageVersion: String, javacPath: Path) {
...
+    if (languageVersion == "8") {
+      val jrePath = dir.resolve("jre")
+      val javacJrePath = javacPath.getParent.getParent.resolve("jre")
+      Files
+        .walk(javacJrePath)
+        .forEach(source => {
+          val destination = jrePath.resolve(javacJrePath.relativize(source))
+          Files.copy(source, destination)
+        })
+    }
```
Comment (varungandhi-src) [inline lsif-java/src/main/scala/com/sourcegraph/lsif_java/buildtools/GradleJavaCompiler.scala:123]: 1. Is it intentional that for languageVersion == 8, we will perform two sets of copies? If not, should it be an`if lang == 8 then do X else do Y` instead of `do Y; if lang == 8 do X?
2. The comment says "JDK 8 has rt.jar in $JDK_HOME/jre/lib" but there is no `lib` in the code below it... I don't understand that. Is that intentional?
3. There is a bunch of code duplication; would be nice to factor it out:
    * either into a small local function if the answer to 1 is Yes.
    * using `if else` should get rid of the duplication if the answer to 1 is No.

File: .jvmopts [hunk 4]
```diff
@@ -2,3 +2,4 @@
 -Xms1G
 -Xmx4G
 -Dfile.encoding=UTF-8
+-Dsbt.server.autostart=true
```
Comment (varungandhi-src) [inline .jvmopts:5]: What does this change do/why is it part of this patch?

File: lsif-java/src/main/scala/com/sourcegraph/lsif_java/buildtools/GradleJavaCompiler.scala (hunk 3 above)
Comment (Strum355) [reply lsif-java/src/main/scala/com/sourcegraph/lsif_java/buildtools/GradleJavaCompiler.scala:123]: 1. JDK 9+ dont have the `/jre` folder anymore, everything was consolidated (and restructured) into only `/lib`
2. Everything from `/jre` is copied, including `/jre/lib/*`. I can probably just copy stuff from `/jre/lib` though, and ignore `/jre/bin`

Comment (varungandhi-src) [reply lsif-java/src/main/scala/com/sourcegraph/lsif_java/buildtools/GradleJavaCompiler.scala:123]: > JDK 9+ dont have the /jre folder anymore, everything was consolidated (and restructured) into only /lib

👍 . FWIW, I think it may be helpful to explain some of this in the comment. It seems a bit cryptic right now, since it's talking about two different jars in the two different ones.

Perhaps something like:

```
// In JDK 8, rt.jar in $JDK_HOME/jre/lib and <blah> is in $JDK_HOME/lib
// In JDK 9+, both of these are consolidated under $JDK_HOME/lib
```

> I can probably just copy stuff from /jre/lib though, and ignore /jre/bin

That seems like a good idea.

File: lsif-java/src/main/scala/com/sourcegraph/lsif_java/buildtools/GradleJavaCompiler.scala [hunk 5]
```diff
@@ -98,6 +99,43 @@ case class GradleJavaCompiler(languageVersion: String, javacPath: Path) {
...
+            val destPath = destination.resolve(source.relativize(t))
+            try {
+              Files.copy(t, destPath)
+            } catch {
+              case _: NoSuchFileException =>
+                return
+            }
+          })
+      }
+
```
Comment (varungandhi-src) [inline lsif-java/src/main/scala/com/sourcegraph/lsif_java/buildtools/GradleJavaCompiler.scala:123]:
```suggestion
    val copyFiles =
      (source: Path, destination: Path) => {
        Files
          .walk(source)
          .forEach(t => {
            val destPath = destination.resolve(source.relativize(t))
            try {
              Files.copy(t, destPath)
            } catch {
              case _: NoSuchFileException =>
                return
            }
          })
      }

    // For compile{Test}Kotlin when using jvm toolchains, we need to have access
    // to JDK internals found in <java-installation-path>/lib in JDK 9+,
    // as well as <java-installation-path>/jre/lib in JDK <=8, else we get
    // "no class roots are found in the JDK path" from the compile{Test}Kotlin tasks.
    // https://docs.oracle.com/en/java/javase/12/migrate/index.html#JSMIG-GUID-A78CC891-701D-4549-AA4E-B8DD90228B4B
```

Nit: Please put the comment closer the code it pertains to.

**Review by varungandhi-src — APPROVED** [review]
LGTM, probably could be compressed a bit more but thanks for simplifying away the class definition.

File: lsif-java/src/main/scala/com/sourcegraph/lsif_java/buildtools/GradleJavaCompiler.scala [hunk 6]
```diff
@@ -98,6 +99,39 @@ case class GradleJavaCompiler(languageVersion: String, javacPath: Path) {
...
+    val javacLibPath = javaHome.resolve("lib")
+    copyFiles(javacLibPath, libPath)
+
+    if (languageVersion == "8") {
+      val jreLibPath = dir.resolve("jre").resolve("lib")
+      Files.createDirectories(jreLibPath.getParent)
+      val javacJreLibPath = javaHome.resolve("jre").resolve("lib")
+
+      copyFiles(javacJreLibPath, jreLibPath)
+    }
```
Comment (varungandhi-src) [inline lsif-java/src/main/scala/com/sourcegraph/lsif_java/buildtools/GradleJavaCompiler.scala:134]: Nice and compact! 🍬
