### PR TITLE
fixes range deriving for constructs incl classes/interfaces

### LINKED ISSUE #109: Incorrect range for interface definition
https://github.com/sourcegraph/lsif-java/blob/756563ffca0a55d49141fc2c94d75af729c30744/tests/snapshots/src/main/generated/minimized/Interfaces.java#L3-L4

```diff
-- obtained
++ expected
  public interface Interfaces {
- //     ^^^^^^^^^^ definition minimized/Interfaces#
+ //               ^^^^^^^^^^ definition minimized/Interfaces#

```

### PR DESCRIPTION
**Pull request by Strum355**
Uses text search derived from previous com.sun.source lsif-java (Kotlin edition), which is originally derived from georgewfraser's java language server. Closes #109 

Of particular note is that the current changes cause definition occurence to [not be emitted](https://github.com/sourcegraph/lsif-java/pull/121/files#diff-1c43dc4d39a78f8bfeee7dbff8bd285a2cd2c711e57d8053586575921be9230cL325). The reference to this no longer existing definition occurrence still gets emitted, we can either follow up with a PR or fix it in this PR. 

I feel like moving parts of `SemanticdbVisitor.semanticdbRange(...)` to the `RangeFinder` class to keep more of the logic together, but I will revisit this tomorrow.

### CODE REVIEW

File: semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/RangeFinder.java [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+            .setEndLine((int) lineMap.getLineNumber(endPos) - 1)
+            .setEndCharacter((int) lineMap.getColumnNumber(endPos) - 1)
+            .build();
+    return Optional.of(range);
+  }
+
+  private static int findNameIn(CompilationUnitTree root, CharSequence name, int start, int end) {
+    String contents;
+    try {
+      contents = root.getSourceFile().getCharContent(true).toString();
```
Comment (olafurpg) [inline semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/RangeFinder.java:46]: This may be an expensive operation, we should reuse the string between invocations.

File: semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/RangeFinder.java [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+    } catch (IOException e) {
+      return -1;
+    }
+
+    if (end == -1) {
+      end = contents.length();
+    }
+
+    Matcher matcher = Pattern.compile("\\b" + name + "\\b").matcher(contents);
```
Comment (olafurpg) [inline semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/RangeFinder.java:55]: Regexp can be pretty expensive. It looks like we could get away with `indexOf(" " + name + " ")`

File: semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/SemanticdbVisitor.java [hunk 3]
```diff
@@ -103,8 +106,11 @@ public Void visitClass(ClassTree node, Void unused) {
   public Void visitMethod(MethodTree node, Void unused) {
     if (node instanceof JCTree.JCMethodDecl) {
       JCTree.JCMethodDecl meth = (JCTree.JCMethodDecl) node;
-      emitSymbolOccurrence(
-          meth.sym, meth, Role.DEFINITION, CompilerRange.FROM_POINT_TO_SYMBOL_NAME);
+      CompilerRange range = CompilerRange.FROM_POINT_TO_SYMBOL_NAME;
+      if (meth.params.isEmpty() && (meth.sym.flags() & Flags.GENERATEDCONSTR) != 0L) {
```
Comment (olafurpg) [inline semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/SemanticdbVisitor.java:110]: Minor: might be worth commenting why this is needed here. It looks like we're specifically targeting only constructors? Is there a difference between this and `name.contentMatches("<init>")`? Is it possible to reuse the logic between this line and the one in `RangeFinder`?

**Review by olafurpg — CHANGES_REQUESTED** [review]
This looks great! Really nice to have this bug fixed. A few minor comments on style and performance.


I recommend running the benchmarks https://sourcegraph.github.io/lsif-java/docs/benchmarks.html just to validate if the optimizations make a difference. I suspect you won't see a difference in caching the file contents from the compilation unit because we compile virtual files in the benchmark, but the speedup might actually be important for build tools that use a different source file implementation.

File: semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/RangeFinder.java (hunk 2 above)
Comment (Strum355) [reply semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/RangeFinder.java:55]: That would fail to match a generic class of the form `Classname<T>`, but I think just `indexOf(" " + name)` should be good enough

**Comment by Strum355** [comment]
This branch:
```
[info] Benchmark                           (lib)  Mode  Cnt     Score    Error  Units
[info] CompileBench.compile            bytebuddy    ss   10  1371.189 ± 46.755  ms/op
[info] CompileBench.compile                guava    ss   10  1860.100 ± 94.912  ms/op
[info] CompileBench.compileSemanticdb  bytebuddy    ss   10  1684.466 ± 32.033  ms/op
[info] CompileBench.compileSemanticdb      guava    ss   10  2292.896 ± 45.351  ms/op
```

Current main:
```
[info] Benchmark                           (lib)  Mode  Cnt     Score    Error  Units
[info] CompileBench.compile            bytebuddy    ss   10  1379.276 ± 37.184  ms/op
[info] CompileBench.compile                guava    ss   10  1870.692 ± 95.841  ms/op
[info] CompileBench.compileSemanticdb  bytebuddy    ss   10  1662.590 ± 39.720  ms/op
[info] CompileBench.compileSemanticdb      guava    ss   10  2282.368 ± 70.845  ms/op
```

File: semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/SemanticdbVisitor.java (hunk 3 above)
Comment (Strum355) [reply semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/SemanticdbVisitor.java:110]: The difference being, my thinking at the time was that only the no-param constructor would ever be generated, but I realise now this doesn't hold true for the new `record` class types, so I'll revisit this line.

File: semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/RangeFinder.java (hunk 1 above)
Comment (Strum355) [reply semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/RangeFinder.java:46]: I did a tiny bit of hunting through the jdk types, I saw some references to caching but am not sure if those types are the ones used in our code paths. The benchmarks however appear to show no adverse performance effects

**Review by olafurpg — APPROVED** [review]
Awesome, please ignore the perf comments. 

LGTM 👍

**Comment by olafurpg** [comment]
Actually, we should still reuse the string for the compilation unit source code because it's unlikely to appear as a bottleneck in our benchmarks.

File: semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/RangeFinder.java (hunk 1 above)
Comment (Strum355) [reply semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/RangeFinder.java]: Now caching computation of such :+1:

File: semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/SemanticdbVisitor.java (hunk 3 above)
Comment (olafurpg) [reply semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/SemanticdbVisitor.java:110]: We can BTW add Java 15 code to the test suite. Alternatively, we can change the default minimized project to Java 15

Comment (olafurpg) [reply semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/SemanticdbVisitor.java:110]: I wouldn't worry too much about Java 15 however, we can deal with it later. I suspect very few users are on Java 15 right now.

File: semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/RangeFinder.java [hunk 4]
```diff
@@ -0,0 +1,68 @@
...
+import java.io.IOException;
+import java.util.HashMap;
+import java.util.Optional;
+import java.util.regex.Matcher;
+import java.util.regex.Pattern;
+
+import static com.sourcegraph.semanticdb_javac.Debugging.pprint;
+
+public class RangeFinder {
+  private static final HashMap<CompilationUnitTree, String> contentsCache = new HashMap<>();
```
Comment (olafurpg) [inline semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/RangeFinder.java:19]: We should avoid static caches at all costs because they end up holding lots of memory. I don't think we even need a cache, we can store `SemanticdbVisitor.semanticdbText()` in a field.

**Review by olafurpg — CHANGES_REQUESTED** [review]

File: semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/RangeFinder.java (hunk 4 above)
Comment (Strum355) [reply semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/RangeFinder.java:19]: Yep, this shouldve been obvious :facepalm: Not sure I follow with `semanticdbText()` though :thinking:

Comment (olafurpg) [reply semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/RangeFinder.java:19]: I think we can store the source code string in the constructor here https://github.com/sourcegraph/lsif-java/blob/48bce73664383381c85211a781a427924abae1a2/semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/SemanticdbVisitor.java#L48

Comment (Strum355) [reply semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/RangeFinder.java:19]: Ah yes I see that now :+1:

File: semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/SemanticdbVisitor.java [hunk 5]
```diff
@@ -213,13 +230,15 @@ private String semanticdbSymbol(Symbol sym) {
     }
   }
 
-  private String semanticdbText() {
-    if (!options.includeText) return "";
+  private String semanticdbText(boolean noop) {
```
Comment (olafurpg) [inline semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/SemanticdbVisitor.java:233]: I think we can leave this method unchanged.

File: semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/SemanticdbVisitor.java [hunk 6]
```diff
@@ -39,13 +41,15 @@ public SemanticdbVisitor(
...
     this.options = options;
+    this.trees = Trees.instance(task);
     if (event.getCompilationUnit() instanceof JCTree.JCCompilationUnit) {
       this.endPosTable = ((JCTree.JCCompilationUnit) event.getCompilationUnit()).endPositions;
     } else {
       this.endPosTable = new EmptyEndPosTable();
     }
     this.occurrences = new ArrayList<>();
     this.symbolInfos = new ArrayList<>();
+    // this.source = "";
```
Comment (olafurpg) [inline semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/SemanticdbVisitor.java:52]:
```suggestion
    this.source = semanticdbText();
```

File: semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/SemanticdbVisitor.java [hunk 7]
```diff
@@ -56,7 +60,7 @@ public SemanticdbVisitor(
         .setSchema(Semanticdb.Schema.SEMANTICDB4)
         .setLanguage(Semanticdb.Language.JAVA)
         .setUri(semanticdbUri())
-        .setText(semanticdbText())
+        .setText(semanticdbText(!options.includeText))
```
Comment (olafurpg) [inline semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/SemanticdbVisitor.java:63]:
```suggestion
        .setText(options.includeText ? this.source : "")
```

**Review by olafurpg — CHANGES_REQUESTED** [review]
Minor comments

**Review by olafurpg — APPROVED** [review]
LGTM 👍 You may need to run `fixAll` to please the CI.

This is ready to merge 🚀
